### ISSUE TITLE
About paper.

### ISSUE THREAD

**Issue by zhaihongjia** [yu-li/TCMonoDepth#3]
Hi，thank you for sharing. It's a great job. I haven't found the paper. Can you share it to me? zhaihongjiaxjtu@163.com,thanks

**Comment by yu-li** [comment]
> Hi，thank you for sharing. It's a great job. I haven't found the paper. Can you share it to me? [zhaihongjiaxjtu@163.com](mailto:zhaihongjiaxjtu@163.com),thanks

Hi please find it via
https://openaccess.thecvf.com/content/ICCV2021W/PBDL/papers/Li_Enforcing_Temporal_Consistency_in_Video_Depth_Estimation_ICCVW_2021_paper.pdf
