### ISSUE TITLE
Temporal filtering

### ISSUE THREAD

**Issue by dpredie** [yu-li/TCMonoDepth#4]
Hi, is the temporal filtering done on the pretrained model itself or in demo.py? I thought Midasnet is not temporally consistent. Would you mind pointing out how you did the temporal filtering?

**Comment by SYL-322** [comment]
Hi, please find details in our paper
https://openaccess.thecvf.com/content/ICCV2021W/PBDL/papers/Li_Enforcing_Temporal_Consistency_in_Video_Depth_Estimation_ICCVW_2021_paper.pdf
