### ISSUE TITLE
Assertion Error in Colab

### ISSUE THREAD

**Issue by CGMikeG** [yu-li/TCMonoDepth#6]
I am not sure if this is currently a torch issue but would anybody happen to know how to fix this.

/content/TCMonoDepth
Run Video Depth Sample 
Initialize
Device: cuda
Creating model...
model size is  0.5x
Loading model from /content/TCMonoDepth/weights/_ckpt_small.pt.tar
Loading model done...
<VideoCapture 0x7f581ca43fd0>
Error opening video stream or file
Traceback (most recent call last):
  File "processVideoFile.py", line 187, in <module>
    run(args)
  File "processVideoFile.py", line 155, in run
    write_video(outputfile, color_list, fps)
  File "processVideoFile.py", line 22, in write_video
    assert (len(output_list) > 0)
AssertionError

**Comment by SYL-322** [comment]
Hi,
This error means that you are not getting any depth output. It may be related to the input video. 
By the way, we don't have a file named processVideoFile.py. You can try our original code.

**Comment by CGMikeG** [comment]
thanks
